INSERT INTO categoria (nome) VALUES
('Eletrônicos'),
('Eletrodomésticos'),
('Roupas e Acessórios'),
('Beleza e Cuidados Pessoais'),
('Saúde e Bem-estar'),
('Alimentos e Bebidas'),
('Casa e Decoração'),
('Esportes e Lazer'),
('Automotivo'),
('Brinquedos e Jogos'),
('Papelaria e Escritório'),
('Livros e Mídia'),
('Música e Instrumentos Musicais'),
('Pet Shop'),
('Ferramentas e Construção'),
('Relógios e Óculos'),
('Energia Solar e Sustentabilidade'),
('Segurança e Monitoramento'),
('Viagem e Turismo'),
('Serviços Digitais');

INSERT INTO produto (nome, descricao, preco, idcategoria) VALUES
('Smartphone', 'Smartphone de última geração com 128GB de memória interna e câmera de 48MP', 2999.90, (select id from categoria where nome = 'Eletrônicos')),
('Geladeira Frost Free', 'Geladeira Frost Free de 400L com tecnologia inverter', 1999.99, (select id from categoria where nome = 'Eletrodomésticos')),
('Camiseta Masculina', 'Camiseta 100% algodão, disponível em várias cores e tamanhos', 39.90, (select id from categoria where nome = 'Roupas e Acessórios')),
('Perfume Feminino', 'Perfume com notas florais, ideal para uso diário', 129.90, (select id from categoria where nome = 'Beleza e Cuidados Pessoais')),
('Kit Saúde', 'Kit de suplementos alimentares para emagrecimento e energia', 149.90, (select id from categoria where nome = 'Saúde e Bem-estar')),
('Cerveja Artesanal', 'Cerveja artesanal, sabor único com 5% de teor alcoólico', 19.90, (select id from categoria where nome = 'Alimentos e Bebidas')),
('Sofá Retrátil', 'Sofá retrátil de 3 lugares, perfeito para sala de estar', 1499.00, (select id from categoria where nome = 'Casa e Decoração')),
('Bola de Futebol', 'Bola de futebol profissional para jogos e treinos', 69.90, (select id from categoria where nome = 'Esportes e Lazer')),
('Pneus para Carro', 'Pneus de alta performance, 205/55 R16', 399.90, (select id from categoria where nome = 'Automotivo')),
('Brinquedo Educativo', 'Brinquedo educativo para crianças de 3 a 6 anos', 49.90, (select id from categoria where nome = 'Brinquedos e Jogos')),
('Caderno Universitário', 'Caderno universitário com 100 folhas pautadas', 12.90, (select id from categoria where nome = 'Papelaria e Escritório')),
('Livro de Tecnologia', 'Livro sobre as tendências em tecnologia e inovação', 59.90, (select id from categoria where nome = 'Livros e Mídia')),
('Violão Acústico', 'Violão acústico com 6 cordas e excelente qualidade de som', 499.90, (select id from categoria where nome = 'Música e Instrumentos Musicais')),
('Ração para Cães', 'Ração premium para cães de porte médio, com 10kg', 89.90, (select id from categoria where nome = 'Pet Shop')),
('Furadeira Elétrica', 'Furadeira elétrica com 350W, ideal para uso doméstico', 139.90, (select id from categoria where nome = 'Ferramentas e Construção')),
('Óculos de Sol', 'Óculos de sol com proteção UV400 e design moderno', 99.90, (select id from categoria where nome = 'Relógios e Óculos')),
('Painel Solar', 'Kit de painel solar para gerar energia limpa em casa', 2599.00, (select id from categoria where nome = 'Energia Solar e Sustentabilidade')),
('Câmera de Segurança', 'Câmera de segurança sem fio com resolução HD', 249.90, (select id from categoria where nome = 'Segurança e Monitoramento')),
('Mochila de Viagem', 'Mochila impermeável com capacidade para 40L', 129.90, (select id from categoria where nome = 'Viagem e Turismo')),
('Assinatura de Software', 'Assinatura mensal para software de edição de vídeo', 29.90, (select id from categoria where nome = 'Serviços Digitais'));

INSERT INTO usuario (cpf, nome, email, datanascimento, telefone) VALUES
('12345678901', 'João Silva', 'joao.silva@email.com', '1990-05-15', '11987654321'),
('23456789012', 'Maria Oliveira', 'maria.oliveira@email.com', '1985-07-22', '11976543210'),
('34567890123', 'Carlos Souza', 'carlos.souza@email.com', '1982-03-10', '11975432109'),
('45678901234', 'Ana Pereira', 'ana.pereira@email.com', '1993-11-02', '11974321098'),
('56789012345', 'Ricardo Santos', 'ricardo.santos@email.com', '1997-02-25', '11973210987'),
('67890123456', 'Fernanda Lima', 'fernanda.lima@email.com', '2000-08-30', '11972109876'),
('78901234567', 'Paulo Costa', 'paulo.costa@email.com', '1995-01-18', '11971098765'),
('89012345678', 'Juliana Alves', 'juliana.alves@email.com', '1992-06-12', '11970987654'),
('90123456789', 'Roberto Gomes', 'roberto.gomes@email.com', '1987-09-20', '11969876543'),
('01234567890', 'Larissa Martins', 'larissa.martins@email.com', '1989-12-05', '11968765432');
